# Generated by Django 5.1.2 on 2024-12-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='barber',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
    ]
