# Generated by Django 5.1.2 on 2025-02-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberwebapp', '0002_alter_appointment_options_alter_barber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barberwebapp.barber'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barberwebapp.barber'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barberwebapp.barber'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='barber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barberwebapp.barber'),
        ),
    ]
